require("config.def")

require("config.lazy")

require("lazy").setup("plugins")

require("config.guides")
require("config.general")
require("config.mason")
require("config.conform")
require("config.lsp")
require("config.languages")
require("config.scope")
require("config.fzf")
require("config.theme")
-- require("config.sidebar")
-- require("config.cmp")
require("config.neovide")
require("config.keybindings")
require("config.lline")
require("config.tree")
require("config.oil")
require("config.telescope")
require("config.colorize")
require("config.bline")
require("config.termedit")
require("config.undotree")
require("config.ts_autotag")
require("config.flutter")
require("config.luasnip")
require("config.dap_conf")
require("config.term_cursor")
require("config.blink_conf")
require("config.ui")
require("config.sshfs_conf")
