require("config.lazy")

require("lazy").setup("plugins")

require("config.general")
require("config.lsp")
require("config.languages")
require("config.scope")
require("config.theme")
require("config.neovide")
require("config.keybindings")
require("config.lline")
require("config.tree")
require("config.oil")
require("config.colorize")
require("config.bline")
require("config.termedit")
require("config.undotree")
require("config.ts_autotag")
require("config.flutter")
require("config.luasnip")
require("config.term_cursor")
require("config.ui")
